export const $ = (id) => document.getElementById(id);

export function createRefs() {
  return {
    round: $("round"),
    hp: $("hp"),
    gold: $("gold"),
    streak: $("streak"),
    income: $("income"),
    level: $("level"),
    levelXp: $("levelXp"),
    levelXpBar: $("levelXpBar"),
    fieldXpBar: $("fieldXpBar"),
    levelUp: $("levelUp"),
    battle: $("battle"),
    shop: $("shop"),
    oddsToggle: $("oddsToggle"),
    oddsPopover: $("oddsPopover"),
    shopLock: $("shopLock"),
    shopOdds: $("shopOdds"),
    boardCapacity: $("boardCapacity"),
    boardCapacityMain: $("boardCapacityMain"),
    boardCapacitySub: $("boardCapacitySub"),
    board: $("board"),
    enemyBoard: $("enemyBoard"),
    bench: $("bench"),
    benchCount: $("benchCount"),
    traits: $("traits"),
    log: $("log"),
    phase: $("phase"),
    unitDetail: $("unitDetail"),
    detailTier: $("detailTier"),
    sellUnit: $("sellUnit"),
    bgmToggle: $("bgmToggle"),
    rankingToggle: $("rankingToggle"),
    rankingClose: $("rankingClose"),
    rankingModal: $("rankingModal"),
    rankingPanel: $("rankingPanel"),
    rankSubmit: $("rankSubmit"),
    rankName: $("rankName"),
    rankSave: $("rankSave"),
    patchNotesModal: $("patchNotesModal"),
    patchNotesTitle: $("patchNotesTitle"),
    patchNotesMeta: $("patchNotesMeta"),
    patchNotesBody: $("patchNotesBody"),
    patchNotesClose: $("patchNotesClose"),
    patchNotesSkipToday: $("patchNotesSkipToday"),
  };
}
